env:
  commonjs: false
  es6: true
  node: true
extends:
  - google
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
plugins: 
  - prettier
rules: {
  new-cap: 0,
  prettier/prettier: error
}
